# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - baranov.rp@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

services:
  - postgresql
before_script:
  - psql -c 'create database users;' -U postgres
  - psql -c 'create database hibernate_module_test;' -U postgres
  - psql -c 'create database sales_car_platform_test;' -U postgres